"""Initial schema for new database

Revision ID: da80514b82ee
Revises: 
Create Date: 2025-05-13 18:59:05.627501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da80514b82ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=150), nullable=True),
    sa.Column('album', sa.String(length=150), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_title'))
        batch_op.drop_index(batch_op.f('ix_song_genre'))
        batch_op.drop_index(batch_op.f('ix_song_artist'))

    op.drop_table('song')
    # ### end Alembic commands ###
